{% set version = "2.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinydashboardplus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinydashboardPlus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinydashboardPlus/shinydashboardPlus_{{ version }}.tar.gz
  sha256: 0bc34cd75f6df1d9c6cb8e7e98e18c5c9c4f739ef54c8d79462597dd1cf3a3cc

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-fresh
    - r-htmltools
    - r-lifecycle
    - r-shiny
    - r-shinydashboard
    - r-waiter
  run:
    - r-base
    - r-fresh
    - r-htmltools
    - r-lifecycle
    - r-shiny
    - r-shinydashboard
    - r-waiter

test:
  commands:
    - $R -e "library('shinydashboardPlus')"           # [not win]
    - "\"%R%\" -e \"library('shinydashboardPlus')\""  # [win]

about:
  home: https://github.com/RinteRface/shinydashboardPlus, https://rinterface.com/shiny/shinydashboardPlus/
  license: GPL-2.0-or-later
  summary: "Extend 'shinydashboard' with 'AdminLTE2' components.  'AdminLTE2' is a free 'Bootstrap 3' dashboard template available at <https://adminlte.io>. Customize boxes, add timelines and a lot more. "
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinydashboardPlus
# Type: Package
# Title: Add More 'AdminLTE2' Components to 'shinydashboard'
# Version: 0.7.0
# Authors@R: c( person("David", "Granjon", email = "dgranjon@ymail.com", role = c("aut", "cre")), person(family = "RinteRface", role = "cph"), person(family = "Almasaeed Studio", role = c("ctb", "cph"), comment = "AdminLTE2 theme for Bootstrap 3"), person("Guang", "Yang", role = c("ctb", "cph"), comment = "ygdashboard original template"), person("Winston", "Chang", role = c("ctb", "cph"), comment = "Functions from shinydashboard"), person("Petr", "Tichy", role = c("ctb", "cph"), comment = "CSS preloader"), person("Victor", "Perrier", email = "victor.perrier@dreamrs.fr", role = "ctb", comment = "improved the shinydashboardPlusGallery"))
# Maintainer: David Granjon <dgranjon@ymail.com>
# Description: Extend 'shinydashboard' with 'AdminLTE2' components.  'AdminLTE2' is a free 'Bootstrap 3' dashboard template available at <https://adminlte.io>. Customize boxes, add timelines and a lot more.
# License: GPL (>= 2) | file LICENSE
# Imports: shiny, htmltools, shinydashboard
# Suggests: styler (>= 1.0.2), shinyAce, shinyWidgets, shinyEffects, shinyjqui, knitr, rmarkdown
# URL: https://github.com/RinteRface/shinydashboardPlus, https://rinterface.com/shiny/shinydashboardPlus/
# BugReports: https://github.com/RinteRface/shinydashboardPlus/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-04-08 07:56:58 UTC; macdavidgranjon
# Author: David Granjon [aut, cre], RinteRface [cph], Almasaeed Studio [ctb, cph] (AdminLTE2 theme for Bootstrap 3), Guang Yang [ctb, cph] (ygdashboard original template), Winston Chang [ctb, cph] (Functions from shinydashboard), Petr Tichy [ctb, cph] (CSS preloader), Victor Perrier [ctb] (improved the shinydashboardPlusGallery)
# Repository: CRAN
# Date/Publication: 2019-04-08 08:20:03 UTC
