{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinydashboardplus
  version: {{ version|replace("-", "_") }}

source:
  fn: shinydashboardPlus_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinydashboardPlus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinydashboardPlus/shinydashboardPlus_{{ version }}.tar.gz
  sha256: 8bfe7cee7e550bbb417fda5f7d45c21a877fd3ec511600f372546d95fb4baf43

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-shiny
    - r-shinydashboard
  run:
    - r-base
    - r-htmltools
    - r-shiny
    - r-shinydashboard

test:
  commands:
    - $R -e "library('shinydashboardPlus')"           # [not win]
    - "\"%R%\" -e \"library('shinydashboardPlus')\""  # [win]

about:
  home: https://github.com/DivadNojnarg/shinydashboardPlus, http://130.60.24.205/shinydashboardPlus/#
  license: GPL-2
  summary: 'Extend ''shinydashboard'' with ''AdminLTE2'' components.  ''AdminLTE2'' is a free
    ''Bootstrap 3'' dashboard template available at <https://adminlte.io>. Customize
    boxes, add timelines and a lot more. '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
